// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241128193643_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Content = "Working on .Net Project",
                            CreatedOn = new DateTime(2024, 11, 29, 1, 4, 52, 537, DateTimeKind.Unspecified),
                            Title = ".Net Project"
                        },
                        new
                        {
                            id = 2,
                            Content = "Working on Lakshya SAP Project",
                            CreatedOn = new DateTime(2024, 11, 29, 1, 4, 52, 537, DateTimeKind.Unspecified),
                            Title = "Kellton SAP Project"
                        },
                        new
                        {
                            id = 3,
                            Content = "Working on Lakshya S4 Project",
                            CreatedOn = new DateTime(2024, 11, 29, 1, 4, 52, 537, DateTimeKind.Unspecified),
                            Title = "Kellton S4 Project"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
